name: CI/CD Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "DEPLOY_KEY is: $DEPLOY_KEY"
        echo "SERVER_HOST is: $DEPLOY_KEY"
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/id_rsa $HOST << 'ENDSSH'
        set -e
        cd ~/public_html || exit 1
        pwd
        git fetch origin master
        git reset --hard FETCH_HEAD
        git clean -df
        git pull
        ENDSSH
        
      env:
        HOST: ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
