name: Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run in Alpine container
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/sh
          args: |
            -c "
            apk add --no-cache gettext &&
            envsubst < .env.template > .env &&
            cat .env
            "

      - name: Deploy to server
        run: |
          scp .env $HOST:~/public_html/.env
          ssh -o StrictHostKeyChecking=no $HOST << 'EOF'
            set -e  
            cd ~/public_html || exit 1
            git fetch origin master
            git reset --hard FETCH_HEAD
            git clean -df
            rm -rf vendor composer.lock
            composer i
          EOF
          
        env:
          HOST: ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}